version: '3'
services:
  observer:
    depends_on: [chrome]
    image: getcarrier/observer:latest
    environment:
      - remote=chrome:4444
      - listener=chrome:9999
      - ffmpeg_path=ffmpeg
      #- INFLUX_HOST=carrier-influx
      #- INFLUX_PORT=8086
      #- INFLUX_DB=perfui
    volumes:
      - /tmp/reports:/tmp/reports
      - ${PWD}/tests/data/:/tmp/scenarios
    command: '-f /tmp/scenarios/real-world.side -fp 100 -si 400 -tl 500 -r xml -r html'
  chrome:
    image: getcarrier/observer-chrome:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999"]
      interval: 1m
      timeout: 10s
      retries: 3
    container_name: chrome
    ports:
      - 4444:4444
      - 9999:9999
